print("!DSH_START");
print("!  Success  !");
delay(1000);
print("!  Success  !");
delay(500);
print("!  Success  !");
delay(250);
print("!  Success  !");
delay(125);
print("!  Success  !");
print("!DSH_STOP");